install:
  - java -version
  - java -jar ASCIIGenome.jar -v
  - java -jar ASCIIGenome.jar -ni -x "bookmark && zo && zo && bookmark"
  - java -jar ASCIIGenome.jar -nf -ni -x command.ag hg19_genes_head.gtf.gz
